Repository: Products.CMFPlone


Branch: refs/heads/5.2.x
Date: 2019-11-14T21:00:43+06:00
Author: Md Nazrul Islam (nazrulworld) <connect2nazrul@gmail.com>
Commit: https://github.com/plone/Products.CMFPlone/commit/1858ea589412fa2959aaa63482ed6c0148944f30

Now PasswordResetView::getErrors is called, before trying to reset password.
Issue: https://github.com/plone/Products.CMFPlone/issues/2917

Files changed:
M Products/CMFPlone/browser/login/password_reset.py

b"diff --git a/Products/CMFPlone/browser/login/password_reset.py b/Products/CMFPlone/browser/login/password_reset.py\nindex f178e8c80..c56810c85 100644\n--- a/Products/CMFPlone/browser/login/password_reset.py\n+++ b/Products/CMFPlone/browser/login/password_reset.py\n@@ -117,6 +117,9 @@ def _auto_login(self, userid, password):\n         return\n \n     def _reset_password(self, pw_tool, randomstring):\n+        state = self.getErrors()\n+        if state:\n+            return self.form()\n         userid = self.request.form.get('userid')\n         password = self.request.form.get('password')\n         try:\n"

Repository: Products.CMFPlone


Branch: refs/heads/5.2.x
Date: 2019-11-14T21:20:53+06:00
Author: Md Nazrul Islam (nazrulworld) <connect2nazrul@gmail.com>
Commit: https://github.com/plone/Products.CMFPlone/commit/140b86e5709d8be6e760626107fece5d8130b583

changes log added in news directory

Files changed:
A news/2917.bugfix

b'diff --git a/news/2917.bugfix b/news/2917.bugfix\nnew file mode 100644\nindex 000000000..e641d46b5\n--- /dev/null\n+++ b/news/2917.bugfix\n@@ -0,0 +1,2 @@\n+Fix: PasswordResetView::getErrors is called, this ensures password is validated through RegistrationTool before attempting to reset password.\n+[nazrulword]\n'

Repository: Products.CMFPlone


Branch: refs/heads/5.2.x
Date: 2019-11-14T18:13:38+01:00
Author: Alessandro Pisa (ale-rt) <alessandro.pisa@gmail.com>
Commit: https://github.com/plone/Products.CMFPlone/commit/a2ebf1d40221d1d896588e91c6e9a99b309731a1

Merge pull request #2982 from nazrulworld/5.2.x

Fix #2917: Now PasswordResetView::getErrors is called

Files changed:
A news/2917.bugfix
M Products/CMFPlone/browser/login/password_reset.py

b"diff --git a/Products/CMFPlone/browser/login/password_reset.py b/Products/CMFPlone/browser/login/password_reset.py\nindex f178e8c80..c56810c85 100644\n--- a/Products/CMFPlone/browser/login/password_reset.py\n+++ b/Products/CMFPlone/browser/login/password_reset.py\n@@ -117,6 +117,9 @@ def _auto_login(self, userid, password):\n         return\n \n     def _reset_password(self, pw_tool, randomstring):\n+        state = self.getErrors()\n+        if state:\n+            return self.form()\n         userid = self.request.form.get('userid')\n         password = self.request.form.get('password')\n         try:\ndiff --git a/news/2917.bugfix b/news/2917.bugfix\nnew file mode 100644\nindex 000000000..e641d46b5\n--- /dev/null\n+++ b/news/2917.bugfix\n@@ -0,0 +1,2 @@\n+Fix: PasswordResetView::getErrors is called, this ensures password is validated through RegistrationTool before attempting to reset password.\n+[nazrulword]\n"

