Repository: plone.openid


Branch: refs/heads/master
Date: 2019-03-29T15:39:27+01:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.openid/commit/beeabfb3b9541e192a16df43dfbf3356399d8ec9

Fixed error caused by PAS inserting `login=None` in the openid query.

Fixes https://github.com/plone/plone.openid/issues/10

Files changed:
M CHANGES.rst
M plone/openid/plugins/oid.py

b"diff --git a/CHANGES.rst b/CHANGES.rst\nindex 6ddc82f..dbc9738 100644\n--- a/CHANGES.rst\n+++ b/CHANGES.rst\n@@ -4,7 +4,9 @@ Changelog\n 2.0.5 (unreleased)\n ------------------\n \n-- Nothing changed yet.\n+- Fixed error caused by PAS inserting ``login=None`` in the openid query.\n+  Fixes `issue 10 <https://github.com/plone/plone.openid/issues/10>`_.\n+  [maurits]\n \n \n 2.0.4 (2015-03-21)\ndiff --git a/plone/openid/plugins/oid.py b/plone/openid/plugins/oid.py\nindex 28b586c..4660317 100644\n--- a/plone/openid/plugins/oid.py\n+++ b/plone/openid/plugins/oid.py\n@@ -143,6 +143,12 @@ def authenticateCredentials(self, credentials):\n             # or python-openid will complain\n             query = credentials.copy()\n             del query['extractor']\n+            if 'login' in query and query['login'] is None:\n+                # PAS has tried to lowercase the login, but login was not in\n+                # the credentials, so it is now None.\n+                # This would result in an AttributeError in consumer.complete,\n+                # so we remove it.\n+                del query['login']\n \n             result=consumer.complete(query, self.REQUEST.ACTUAL_URL)\n             identity=result.identity_url\n"

